name: Converte Issues para Docs

on:
  issues:
    types:
      - edited

jobs:
  issue_to_markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: eunjae-lee/issue-to-markdown@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          dest: "./doc/issues"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs: update doc/issues'
